'''Tiferet Streamlit – Asset Constants'''

# *** constants

# ** constant: VIEW_NOT_INITIALIZED_ID
VIEW_NOT_INITIALIZED_ID = 'VIEW_NOT_INITIALIZED'

# ** constant: PAGE_NOT_FOUND_ID
PAGE_NOT_FOUND_ID = 'PAGE_NOT_FOUND'

# ** constant: VIEW_RENDER_FAILED_ID
VIEW_RENDER_FAILED_ID = 'VIEW_RENDER_FAILED'

# ** constant: INVALID_VIEW_TYPE_ID
INVALID_VIEW_TYPE_ID = 'INVALID_VIEW_TYPE'

# ** constant: SESSION_KEY_PREFIX
SESSION_KEY_PREFIX = 'tiferet'
