'''Tiferet Streamlit – Asset Constants'''

# *** constants

# ** constant: PAGE_NOT_FOUND_ID
PAGE_NOT_FOUND_ID = 'PAGE_NOT_FOUND'

# ** constant: VIEW_RENDER_FAILED_ID
VIEW_RENDER_FAILED_ID = 'VIEW_RENDER_FAILED'

# ** constant: INVALID_VIEW_TYPE_ID
INVALID_VIEW_TYPE_ID = 'INVALID_VIEW_TYPE'

# ** constant: VIEW_SERVICE_ID
VIEW_SERVICE_ID = 'view_service'

# ** constant: INVALID_VIEW_SERVICE_ID
INVALID_VIEW_SERVICE_ID = 'INVALID_VIEW_SERVICE'

# ** constant: SESSION_KEY_PREFIX
SESSION_KEY_PREFIX = 'tiferet'
